### ISSUE TITLE
Can't use js close without js show

### ISSUE THREAD

**Issue by djonatanb** [ghosh/micromodal#142]
I'm not sure I'm correct on this, but it seems that the only function that is population the variable activeModal is the show function. That means that I can't use MicroModal.init() and call MicroModal.close().
Is that intentional? it's not exactly what the demo page in the https://micromodal.now.sh/#usage page. Can you please confirm?
https://github.com/ghosh/micromodal/blob/bc03d6d972caf11dccff557eadcd00b7ab75b2f3/dist/micromodal.js#L342

**Comment by djonatanb** [comment]
The only way I got it to work was by running:
MicroModal.show('modal-id'); // [1]
MicroModal.close(); // [2]

That works because .close does not search for the activeModal, it just uses the one already saved in the variable activeModal. By running `.show()` the code gets the modal and then the close will work.

**Comment by theorlan2** [comment]
Hello,
I solved it by editing the source code on "import MicroModal from 'micromodal/src'" in the method 'showModal' adding 'activeModal = this;' 

`showModal() {  
/* Add this  -> */  
activeModal = this;
}`

The problem is that you have to change the source code in each installation of the package.

**Comment by ghosh** [comment]
Thanks for pointing this out. Will merge PR soon.

**Comment by missmatsuko** [comment]
@ghosh Will this be fixed soon?

**Comment by ghosh** [comment]
Thanks for the patience guys.  Fixed in #113
