### ISSUE TITLE
Close modal opened by data-

### ISSUE THREAD

**Issue by caiotarifa** [ghosh/Micromodal#197]
I commented it on the pull request #113 but I opening a new issue to provide a solution for this error:

```
TypeError: null is not an object (evaluating 'activeModal.closeModalById')
```

Well, I am using with [Turbolinks](https://github.com/turbolinks/turbolinks).

``` javascript
import MicroModal from 'micromodal'

document.addEventListener('turbolinks:load', function () {
  MicroModal.init()
})

document.addEventListener('turbolinks:before-cache', function () {
  MicroModal.close('modal-id')
})
```

**Comment by cnobile2012** [comment]
I made a post on issue 196 but will give a more complete description here because it's a little different than this one.

This happens only when using a second button. Any second button will eventually need to close the modal, but executing `MicroModal.close('tag ID')` does nothing. I traced it through your code and it does execute the internal method `closeModal()` but does nothing and no errors are returned either.
