### ISSUE TITLE
Micromodal isn't defined (Only in IE11)

### ISSUE THREAD

**Issue by itailitai** [ghosh/Micromodal#247]
The library works great on every browser except Internet explorer.
I get the following error: 

> MicroModal is not defined

in the follwing code:
```
<script src="js/micromodal.min.js"></script>
<script>

MicroModal.init({

  openTrigger: 'data-custom-open',
  closeTrigger: 'data-custom-close'
 
});

</script>
```
whereas in every other browser I get no errors whatsoever, everything works flawlessly . I included some polyfills but still the issue persists.

**Comment by ghosh** [comment]
Thanks for opening this issue. Will look into it it.

**Comment by vaskar-nepal** [comment]
Hi,

Any update on this issue? Is their any timeline set for this issue. 

Thanks!

**Comment by Twilliamson90** [comment]
This is due to the production minified library containing arrow functions. Arrow functions are [not supported by IE 11](https://kangax.github.io/compat-table/es6/). In the short term, people can use [v0.4.0](https://unpkg.com/micromodal@0.4.0/dist/micromodal.min.js) of this library which does not use the arrow functions. If the author plans to keep IE 11 support then the babel config will need to be updated to [transform arrow functions](https://babeljs.io/docs/en/babel-plugin-transform-arrow-functions).
