### ISSUE TITLE
Not a11y in Safari

### ISSUE THREAD

**Issue by AndreiIgna** [ghosh/micromodal#8]
After opening the modal, the intro says about accessibility and try hitting `tab` key. It's not working as expected in Safari

**Comment by ghosh** [comment]
@AndreiIgna Thanks for reporting this. I just tested in Safari on my machine it seems to be working fine.

Could you please provide some details about your Safari Version and your OS version?

**Comment by csphere** [comment]
@ghosh I've just reproduced this, I believe.

In chrome, tab behavior is as specified in the demo - tab cycles between the "X" button, continue, and close.

In Safari, the "X" button is focused initially, the first tab press selects the address bar, and subsequent tabs alternates between 1) nothing being apparently selected, and 2) the address bar being again selected.  [Here is a screen recording.](https://drive.google.com/file/d/0B2PaQlc-rpZIRUVMcVpKZFQwcXM/view?usp=sharing)

MacOS Version 10.12.6
Safari Version 11.0 (12604.1.38.1.7)

I will fork now and see if I can find a solution.  Will report back.

**Comment by missmatsuko** [comment]
I think this is the expected behaviour for Safari and not sure if it's wise to "correct" it.
In Safari, it seems like `tab` is used to go through form elements and `alt + tab` is used to navigate through all elements.
I would think that people who use keyboard navigation with Safari would expect this behaviour, or modify their preferences themselves.

https://mcmw.abilitynet.org.uk/mac-tabbing-round-a-web-page-using-the-keyboard/

**Comment by csphere** [comment]
Interesting.  Considering the information @missmatsuko provided, I wonder if a change to either the functionality or documentation would be in order.  If Safari has this behavior, I foresee developers being thrown off when they run into that, especially given the wording... "Try hitting the tab key and notice how the focus stays within the modal itself."

At the very least, I'd suggest a clarification that excludes Safari from the behavior advertised, or points out that [by default] Option-Tab should be used in Safari.

**Comment by missmatsuko** [comment]
Well I think the (only?) way to make tab navigation work for the modal on Safari with default settings would be to have input elements for each action and that seems nonsemantic and hacky. I think leaving the functionality of tabs up to the Safari user makes the most sense. 

I agree that the wording could be changed in the documentation for clarity. It’s a bit tough though, since people navigate the web in many different ways. Maybe a short footnote explaining the default keyboard navigation would be sufficient?

**Comment by csphere** [comment]
I would elect to change the demo/readme text to instead clarify up-front "Try hitting the tab key (option-tab on Safari) and notice how the focus stays within the modal itself."

While I agree that a footnote should be sufficient, I anticipate many people may quickly check out the demo and skim the readme, perhaps missing a footnote entirely until they or someone on their team stumbles across the Safari behavior on accident.

Thanks again for looking into that @missmatsuko.  I was unaware of that behavior as a Safari default and you saved me some time there. 😄

**Comment by kalpeshsingh** [comment]
What if we detect Safari browser and change the `tab` to `tab + alt` on demo page?  
What do you all think?

**Comment by csphere** [comment]
In this case, because you have a developer audience, I think being explicit about the behavior differing between browsers is best.  Issues would arise if a developer found the repo/demo using Safari and then tried to use it in a solution through Chrome, or visa-versa.  If your audience were regular users, then I would agree with you, but while users simply need to know what to press in their current browser, developers need to know needs to be pressed across browsers.

I don't think simply saying "or option-tab in Safari" would devalue this library.  As @missmatsuko said, that is simply the shortcut in Safari for focusing the next field, so it wouldn't be seen as a shortcoming to the a11y you have here.  I believe your idea would fit more as an implementation suggestion in order for consumers of your library to improve their UX (in case they want to let their users know which key combo to press while the modal is open).

**Comment by ghosh** [comment]
@missmatsuko Thank you for your research on this.

@csphere I have “All controls” selected in the Shortcuts pane of the Keyboard pane of System Preferences. That's why hitting the `tab` key seemed to work for me.

@kalpeshsingh Agree with @missmatsuko. I don't this we should change the default tab behavior on Safari, rather we should embrace it. 

The point is to make it intuitive for the end users. If they are already using Safari, they would be accustomed to a certain kind of behaviour on `tab` or in this case `alt + tab`. We should not break this expectation only for our modal.

I think the way forward is to not be explicit about promoting the `tab` key as a focus changer. Maybe we could change the language to something more generic. Maybe something like this:- 

"Tab around the modal to ..." instead of "Hit the `tab` key to..."

Thoughts?

**Comment by missmatsuko** [comment]
@ghosh Totally agree that the wording should be adjusted while leaving the behaviour as is. I’m not sure what the best wording would be, but I think “tab around” still implies pressing the tab key? 

I think a footnote would be the simplest solution, but a good generic phrasing would be better if anyone can come up with one.

Footnote example:
> Navigate using your keyboard *
> * Tab or Option+Tab is on most browsers

**Comment by AndreiIgna** [comment]
I posted this in a hurry, sorry for lack more information.

Saw lots of details here, and yes `alt + tab` works as expected. On first use I was pressing `tab`, nothing happened. On pressing ´space´, the main pages scrolls.

Safari Version 11.0 (13604.1.38.1.6) with default settings
macOS High Sierra 10.13 (17A365)

**Comment by kalpeshsingh** [comment]
@ghosh my bad that I didn't convey my thoughts clearly. 

What if we detect Safari browser and change the `tab` to `tab + alt`  **text** on demo page and not the functionality? Plus a footnote as suggested by @missmatsuko .

We can dynamically show update **text** modal on Safari.
![Message on Safari](https://user-images.githubusercontent.com/13119410/31287541-3c61c7a4-aadf-11e7-9a3c-9686b498f27b.png)

**Comment by csphere** [comment]
I believe the correct generic terminology is "Keyboard-Only Navigation."  Perhaps say something like "Using keyboard-only navigation, move focus between the various controls and notice how focus stays within the modal itself."  ¯\_(ツ)_/¯

**Comment by svinkle** [comment]
Just piping in here, there are two options you need to adjust:

1. In Safari, go to `Safari > Preferences > Advanced` and check the `Press Tab to highlight each item on a webpage`
2. Optionally in macOS Settings, go to `Settings > Keyboard > Shortcuts` and at the bottom, select `Full Keyboard Access: All controls`

Folks who depend on AT would have these enabled already, so no need to change your script or verbiage.
