### ISSUE TITLE
Add React Component(s)

### ISSUE THREAD

**Issue by maracuja-juice** [ghosh/Micromodal#94]
It would be really nice if this library provided a (set of) React component(s)

**Comment by kalpeshsingh** [comment]
Hey @maracuja-juice ,

We have plans to make Micromodal in React and Vue.

It will take some time to cover all that. Seeking your patience here. :D

Parking this issue for now, we will update you as soon as we roll out that.

**Comment by lkopacz** [comment]
Wanted to see if there was an update for this, or if any help was needed?

**Comment by zebapy** [comment]
Why do that instead of using https://github.com/reactjs/react-modal or https://ui.reach.tech/ modal?

**Comment by shikkaba** [comment]
@zebapy why not do it?

**Comment by zebapy** [comment]
@shikkaba reinventing the wheel, etc. I don't see anything in this lib that does accessible modal more successfully than the already existing react modal options. This is a great _vanilla_ js modal.

**Comment by ghosh** [comment]
Micromodal accesses the DOM and does a lot of work under the hood which makes it an easy plug and play solution.

Since most code in React is declarative in nature, building this library in React would mean making choices which would greatly change the footprint and the "feel" of the library. It would in no way be related to how this library functions and would thus become just another react modal library.

There are a lot of fantastic react libraries could meet your requirements. I urge you to reach for them for your needs.

Having said that, I do believe that "re-inventing the wheel" is important for progress and learning. So for you people who are interested in a React solution for Micromodal, here is something I put together while thinking about how it could work. - https://codesandbox.io/s/modal-d7u9d

As you can tell, it feels very different from the current implementation. If you have ideas on how this could be bettered please feel free to pitch in.
